language: erlang

notifications:
  disabled: true

install:
  - wget http://www.quviq.com/downloads/eqcmini.zip
  - unzip eqcmini.zip
  - export ERL_LIBS=.
script: 
  - make deps_eunit 
  - make eunit


otp_release:
  - 17.0
  - R16B03-1
  - R16B02
  - R16B01
  - R16B
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
